# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bb/work/probe_basic-pyqt5-x86/sources/debian/python3-probe-basic/usr/share/configs/probe_basic_lathe/user_dro_display/xyzc_dros/dros_xyzc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dros_xyzc(object):
    def setupUi(self, dros_xyzc):
        dros_xyzc.setObjectName("dros_xyzc")
        dros_xyzc.resize(479, 315)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dros_xyzc.sizePolicy().hasHeightForWidth())
        dros_xyzc.setSizePolicy(sizePolicy)
        dros_xyzc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(dros_xyzc)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_xyzc = QtWidgets.QWidget(dros_xyzc)
        self.widget_xyzc.setObjectName("widget_xyzc")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.widget_xyzc)
        self.verticalLayout_55.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_55.setSpacing(19)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.dros_header_layout = QtWidgets.QWidget(self.widget_xyzc)
        self.dros_header_layout.setMinimumSize(QtCore.QSize(0, 42))
        self.dros_header_layout.setObjectName("dros_header_layout")
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout(self.dros_header_layout)
        self.horizontalLayout_79.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.zero_all_button = MDIButton(self.dros_header_layout)
        self.zero_all_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_all_button.sizePolicy().hasHeightForWidth())
        self.zero_all_button.setSizePolicy(sizePolicy)
        self.zero_all_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_all_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_all_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_all_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zero_all_button.setStyleSheet("MDIButton {\n"
"       font: 14pt \"Bebas Kai\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/zero.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zero_all_button.setIcon(icon)
        self.zero_all_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_all_button.setObjectName("zero_all_button")
        self.horizontalLayout_79.addWidget(self.zero_all_button)
        self.column_header_frame = QtWidgets.QFrame(self.dros_header_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.column_header_frame.sizePolicy().hasHeightForWidth())
        self.column_header_frame.setSizePolicy(sizePolicy)
        self.column_header_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.column_header_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.column_header_frame.setStyleSheet(".QFrame{\n"
"    border-style: solid;\n"
"    border-color: rgb(176, 179,172);\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(90, 90, 90);\n"
"    padding: -5px;\n"
"}")
        self.column_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.column_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.column_header_frame.setObjectName("column_header_frame")
        self.horizontalLayout_168 = QtWidgets.QHBoxLayout(self.column_header_frame)
        self.horizontalLayout_168.setContentsMargins(9, -1, 0, -1)
        self.horizontalLayout_168.setSpacing(18)
        self.horizontalLayout_168.setObjectName("horizontalLayout_168")
        self.work_column_header = StatusLabel(self.column_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_column_header.sizePolicy().hasHeightForWidth())
        self.work_column_header.setSizePolicy(sizePolicy)
        self.work_column_header.setMinimumSize(QtCore.QSize(100, 17))
        self.work_column_header.setMaximumSize(QtCore.QSize(100, 17))
        self.work_column_header.setStyleSheet("QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"    font: 16pt \"Bebas Kai\";\n"
"    padding-left: 6px;\n"
"}")
        self.work_column_header.setAlignment(QtCore.Qt.AlignCenter)
        self.work_column_header.setObjectName("work_column_header")
        self.horizontalLayout_168.addWidget(self.work_column_header)
        self.machine_column_header = QtWidgets.QLabel(self.column_header_frame)
        self.machine_column_header.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.machine_column_header.sizePolicy().hasHeightForWidth())
        self.machine_column_header.setSizePolicy(sizePolicy)
        self.machine_column_header.setMinimumSize(QtCore.QSize(100, 17))
        self.machine_column_header.setMaximumSize(QtCore.QSize(100, 17))
        self.machine_column_header.setStyleSheet("QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"    font: 16pt \"Bebas Kai\";\n"
"}")
        self.machine_column_header.setAlignment(QtCore.Qt.AlignCenter)
        self.machine_column_header.setObjectName("machine_column_header")
        self.horizontalLayout_168.addWidget(self.machine_column_header)
        self.dtg_column_header = QtWidgets.QLabel(self.column_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtg_column_header.sizePolicy().hasHeightForWidth())
        self.dtg_column_header.setSizePolicy(sizePolicy)
        self.dtg_column_header.setMinimumSize(QtCore.QSize(100, 17))
        self.dtg_column_header.setMaximumSize(QtCore.QSize(100, 17))
        self.dtg_column_header.setStyleSheet("QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"    font: 16pt \"Bebas Kai\";\n"
"}")
        self.dtg_column_header.setAlignment(QtCore.Qt.AlignCenter)
        self.dtg_column_header.setObjectName("dtg_column_header")
        self.horizontalLayout_168.addWidget(self.dtg_column_header)
        self.horizontalLayout_79.addWidget(self.column_header_frame)
        self.ref_all_button = ActionButton(self.dros_header_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_all_button.sizePolicy().hasHeightForWidth())
        self.ref_all_button.setSizePolicy(sizePolicy)
        self.ref_all_button.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_all_button.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_all_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_all_button.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_all_button.setObjectName("ref_all_button")
        self.horizontalLayout_79.addWidget(self.ref_all_button)
        self.verticalLayout_55.addWidget(self.dros_header_layout)
        self.dros_x_layout = QtWidgets.QWidget(self.widget_xyzc)
        self.dros_x_layout.setMinimumSize(QtCore.QSize(0, 42))
        self.dros_x_layout.setObjectName("dros_x_layout")
        self.x_axis_dro_layout_3 = QtWidgets.QHBoxLayout(self.dros_x_layout)
        self.x_axis_dro_layout_3.setContentsMargins(0, 2, 0, 2)
        self.x_axis_dro_layout_3.setSpacing(8)
        self.x_axis_dro_layout_3.setObjectName("x_axis_dro_layout_3")
        self.zero_x_button = MDIButton(self.dros_x_layout)
        self.zero_x_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_x_button.sizePolicy().hasHeightForWidth())
        self.zero_x_button.setSizePolicy(sizePolicy)
        self.zero_x_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_x_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_x_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zero_x_button.setStyleSheet("MDIButton {\n"
"       font: 16pt \"Bebas Kai\";\n"
"}")
        self.zero_x_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_x_button.setObjectName("zero_x_button")
        self.x_axis_dro_layout_3.addWidget(self.zero_x_button)
        self.dro_entry_x_main = DROLineEdit(self.dros_x_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_entry_x_main.sizePolicy().hasHeightForWidth())
        self.dro_entry_x_main.setSizePolicy(sizePolicy)
        self.dro_entry_x_main.setMinimumSize(QtCore.QSize(100, 35))
        self.dro_entry_x_main.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dro_entry_x_main.setStyleSheet("DROLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.dro_entry_x_main.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_entry_x_main.setProperty("referenceType", 1)
        self.dro_entry_x_main.setProperty("axisNumber", 0)
        self.dro_entry_x_main.setProperty("latheMode", 0)
        self.dro_entry_x_main.setObjectName("dro_entry_x_main")
        self.x_axis_dro_layout_3.addWidget(self.dro_entry_x_main)
        self.drolabel_machine_x = DROLabel(self.dros_x_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_machine_x.sizePolicy().hasHeightForWidth())
        self.drolabel_machine_x.setSizePolicy(sizePolicy)
        self.drolabel_machine_x.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_x.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt;\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_machine_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_machine_x.setProperty("referenceType", 0)
        self.drolabel_machine_x.setProperty("axisNumber", 0)
        self.drolabel_machine_x.setProperty("latheMode", 0)
        self.drolabel_machine_x.setObjectName("drolabel_machine_x")
        self.x_axis_dro_layout_3.addWidget(self.drolabel_machine_x)
        self.dro_dtg_x = DROLabel(self.dros_x_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_dtg_x.sizePolicy().hasHeightForWidth())
        self.dro_dtg_x.setSizePolicy(sizePolicy)
        self.dro_dtg_x.setMinimumSize(QtCore.QSize(100, 35))
        self.dro_dtg_x.setStyleSheet("DROLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt;\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}\n"
"\n"
"DROLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"DROLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.dro_dtg_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_dtg_x.setProperty("referenceType", 2)
        self.dro_dtg_x.setProperty("axisNumber", 0)
        self.dro_dtg_x.setProperty("latheMode", 0)
        self.dro_dtg_x.setObjectName("dro_dtg_x")
        self.x_axis_dro_layout_3.addWidget(self.dro_dtg_x)
        self.ref_x_button_2 = ActionButton(self.dros_x_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_x_button_2.sizePolicy().hasHeightForWidth())
        self.ref_x_button_2.setSizePolicy(sizePolicy)
        self.ref_x_button_2.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_x_button_2.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_x_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_x_button_2.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_x_button_2.setObjectName("ref_x_button_2")
        self.x_axis_dro_layout_3.addWidget(self.ref_x_button_2)
        self.verticalLayout_55.addWidget(self.dros_x_layout)
        self.dros_y_layout = QtWidgets.QWidget(self.widget_xyzc)
        self.dros_y_layout.setMinimumSize(QtCore.QSize(0, 42))
        self.dros_y_layout.setObjectName("dros_y_layout")
        self.z_axis_dro_layout_7 = QtWidgets.QHBoxLayout(self.dros_y_layout)
        self.z_axis_dro_layout_7.setContentsMargins(0, 2, 0, 2)
        self.z_axis_dro_layout_7.setSpacing(8)
        self.z_axis_dro_layout_7.setObjectName("z_axis_dro_layout_7")
        self.zero_y_button = MDIButton(self.dros_y_layout)
        self.zero_y_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_y_button.sizePolicy().hasHeightForWidth())
        self.zero_y_button.setSizePolicy(sizePolicy)
        self.zero_y_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_y_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_y_button.setStyleSheet("MDIButton {\n"
"       font: 17pt \"Bebas Kai\";\n"
"}")
        self.zero_y_button.setIcon(icon)
        self.zero_y_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_y_button.setObjectName("zero_y_button")
        self.z_axis_dro_layout_7.addWidget(self.zero_y_button)
        self.dro_entry_y_main = DROLineEdit(self.dros_y_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_entry_y_main.sizePolicy().hasHeightForWidth())
        self.dro_entry_y_main.setSizePolicy(sizePolicy)
        self.dro_entry_y_main.setMinimumSize(QtCore.QSize(100, 35))
        self.dro_entry_y_main.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dro_entry_y_main.setStyleSheet("DROLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.dro_entry_y_main.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_entry_y_main.setProperty("referenceType", 1)
        self.dro_entry_y_main.setProperty("axisNumber", 1)
        self.dro_entry_y_main.setProperty("latheMode", 0)
        self.dro_entry_y_main.setObjectName("dro_entry_y_main")
        self.z_axis_dro_layout_7.addWidget(self.dro_entry_y_main)
        self.drolabel_machine_y = DROLabel(self.dros_y_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_machine_y.sizePolicy().hasHeightForWidth())
        self.drolabel_machine_y.setSizePolicy(sizePolicy)
        self.drolabel_machine_y.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_y.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt;\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_machine_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_machine_y.setProperty("referenceType", 0)
        self.drolabel_machine_y.setProperty("axisNumber", 1)
        self.drolabel_machine_y.setProperty("latheMode", 0)
        self.drolabel_machine_y.setObjectName("drolabel_machine_y")
        self.z_axis_dro_layout_7.addWidget(self.drolabel_machine_y)
        self.drolabel_12 = DROLabel(self.dros_y_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_12.sizePolicy().hasHeightForWidth())
        self.drolabel_12.setSizePolicy(sizePolicy)
        self.drolabel_12.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_12.setStyleSheet("DROLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt;\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}\n"
"\n"
"DROLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"DROLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_12.setProperty("referenceType", 2)
        self.drolabel_12.setProperty("axisNumber", 1)
        self.drolabel_12.setProperty("latheMode", 0)
        self.drolabel_12.setObjectName("drolabel_12")
        self.z_axis_dro_layout_7.addWidget(self.drolabel_12)
        self.ref_y_button_2 = ActionButton(self.dros_y_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_y_button_2.sizePolicy().hasHeightForWidth())
        self.ref_y_button_2.setSizePolicy(sizePolicy)
        self.ref_y_button_2.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_y_button_2.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_y_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_y_button_2.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_y_button_2.setObjectName("ref_y_button_2")
        self.z_axis_dro_layout_7.addWidget(self.ref_y_button_2)
        self.verticalLayout_55.addWidget(self.dros_y_layout)
        self.dros_z_layout = QtWidgets.QWidget(self.widget_xyzc)
        self.dros_z_layout.setMinimumSize(QtCore.QSize(0, 42))
        self.dros_z_layout.setObjectName("dros_z_layout")
        self.z_axis_dro_layout_6 = QtWidgets.QHBoxLayout(self.dros_z_layout)
        self.z_axis_dro_layout_6.setContentsMargins(0, 2, 0, 2)
        self.z_axis_dro_layout_6.setSpacing(8)
        self.z_axis_dro_layout_6.setObjectName("z_axis_dro_layout_6")
        self.zero_z_button = MDIButton(self.dros_z_layout)
        self.zero_z_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_z_button.sizePolicy().hasHeightForWidth())
        self.zero_z_button.setSizePolicy(sizePolicy)
        self.zero_z_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_z_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_z_button.setStyleSheet("MDIButton {\n"
"       font: 17pt \"Bebas Kai\";\n"
"}")
        self.zero_z_button.setIcon(icon)
        self.zero_z_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_z_button.setObjectName("zero_z_button")
        self.z_axis_dro_layout_6.addWidget(self.zero_z_button)
        self.dro_entry_z_main = DROLineEdit(self.dros_z_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_entry_z_main.sizePolicy().hasHeightForWidth())
        self.dro_entry_z_main.setSizePolicy(sizePolicy)
        self.dro_entry_z_main.setMinimumSize(QtCore.QSize(100, 35))
        self.dro_entry_z_main.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dro_entry_z_main.setStyleSheet("DROLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.dro_entry_z_main.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_entry_z_main.setProperty("referenceType", 1)
        self.dro_entry_z_main.setProperty("axisNumber", 2)
        self.dro_entry_z_main.setProperty("latheMode", 0)
        self.dro_entry_z_main.setObjectName("dro_entry_z_main")
        self.z_axis_dro_layout_6.addWidget(self.dro_entry_z_main)
        self.drolabel_machine_z = DROLabel(self.dros_z_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_machine_z.sizePolicy().hasHeightForWidth())
        self.drolabel_machine_z.setSizePolicy(sizePolicy)
        self.drolabel_machine_z.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_z.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt;\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_machine_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_machine_z.setProperty("referenceType", 0)
        self.drolabel_machine_z.setProperty("axisNumber", 2)
        self.drolabel_machine_z.setProperty("latheMode", 0)
        self.drolabel_machine_z.setObjectName("drolabel_machine_z")
        self.z_axis_dro_layout_6.addWidget(self.drolabel_machine_z)
        self.dro_dtg_z = DROLabel(self.dros_z_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_dtg_z.sizePolicy().hasHeightForWidth())
        self.dro_dtg_z.setSizePolicy(sizePolicy)
        self.dro_dtg_z.setMinimumSize(QtCore.QSize(100, 35))
        self.dro_dtg_z.setStyleSheet("DROLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt;\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}\n"
"\n"
"DROLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"DROLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.dro_dtg_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_dtg_z.setProperty("referenceType", 2)
        self.dro_dtg_z.setProperty("axisNumber", 2)
        self.dro_dtg_z.setProperty("latheMode", 0)
        self.dro_dtg_z.setObjectName("dro_dtg_z")
        self.z_axis_dro_layout_6.addWidget(self.dro_dtg_z)
        self.ref_z_button_2 = ActionButton(self.dros_z_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_z_button_2.sizePolicy().hasHeightForWidth())
        self.ref_z_button_2.setSizePolicy(sizePolicy)
        self.ref_z_button_2.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_z_button_2.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_z_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_z_button_2.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_z_button_2.setObjectName("ref_z_button_2")
        self.z_axis_dro_layout_6.addWidget(self.ref_z_button_2)
        self.verticalLayout_55.addWidget(self.dros_z_layout)
        self.dros_c_layout = QtWidgets.QWidget(self.widget_xyzc)
        self.dros_c_layout.setMinimumSize(QtCore.QSize(0, 42))
        self.dros_c_layout.setObjectName("dros_c_layout")
        self.z_axis_dro_layout_10 = QtWidgets.QHBoxLayout(self.dros_c_layout)
        self.z_axis_dro_layout_10.setContentsMargins(0, 2, 0, 2)
        self.z_axis_dro_layout_10.setSpacing(8)
        self.z_axis_dro_layout_10.setObjectName("z_axis_dro_layout_10")
        self.zero_c_button = MDIButton(self.dros_c_layout)
        self.zero_c_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_c_button.sizePolicy().hasHeightForWidth())
        self.zero_c_button.setSizePolicy(sizePolicy)
        self.zero_c_button.setMinimumSize(QtCore.QSize(60, 40))
        self.zero_c_button.setMaximumSize(QtCore.QSize(60, 40))
        self.zero_c_button.setStyleSheet("MDIButton {\n"
"       font: 17pt \"Bebas Kai\";\n"
"}")
        self.zero_c_button.setIcon(icon)
        self.zero_c_button.setIconSize(QtCore.QSize(20, 20))
        self.zero_c_button.setObjectName("zero_c_button")
        self.z_axis_dro_layout_10.addWidget(self.zero_c_button)
        self.dro_entry_c_main = DROLineEdit(self.dros_c_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_entry_c_main.sizePolicy().hasHeightForWidth())
        self.dro_entry_c_main.setSizePolicy(sizePolicy)
        self.dro_entry_c_main.setMinimumSize(QtCore.QSize(100, 35))
        self.dro_entry_c_main.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dro_entry_c_main.setStyleSheet("DROLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.dro_entry_c_main.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_entry_c_main.setProperty("referenceType", 1)
        self.dro_entry_c_main.setProperty("axisNumber", 5)
        self.dro_entry_c_main.setProperty("latheMode", 0)
        self.dro_entry_c_main.setObjectName("dro_entry_c_main")
        self.z_axis_dro_layout_10.addWidget(self.dro_entry_c_main)
        self.drolabel_machine_c = DROLabel(self.dros_c_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_machine_c.sizePolicy().hasHeightForWidth())
        self.drolabel_machine_c.setSizePolicy(sizePolicy)
        self.drolabel_machine_c.setMinimumSize(QtCore.QSize(100, 35))
        self.drolabel_machine_c.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt;\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_machine_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_machine_c.setProperty("referenceType", 0)
        self.drolabel_machine_c.setProperty("axisNumber", 5)
        self.drolabel_machine_c.setProperty("latheMode", 0)
        self.drolabel_machine_c.setObjectName("drolabel_machine_c")
        self.z_axis_dro_layout_10.addWidget(self.drolabel_machine_c)
        self.dro_dtg_c = DROLabel(self.dros_c_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_dtg_c.sizePolicy().hasHeightForWidth())
        self.dro_dtg_c.setSizePolicy(sizePolicy)
        self.dro_dtg_c.setMinimumSize(QtCore.QSize(100, 35))
        self.dro_dtg_c.setStyleSheet("DROLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt;\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}\n"
"\n"
"DROLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"DROLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.dro_dtg_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_dtg_c.setProperty("referenceType", 2)
        self.dro_dtg_c.setProperty("axisNumber", 5)
        self.dro_dtg_c.setProperty("latheMode", 0)
        self.dro_dtg_c.setObjectName("dro_dtg_c")
        self.z_axis_dro_layout_10.addWidget(self.dro_dtg_c)
        self.ref_c_button_2 = ActionButton(self.dros_c_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_c_button_2.sizePolicy().hasHeightForWidth())
        self.ref_c_button_2.setSizePolicy(sizePolicy)
        self.ref_c_button_2.setMinimumSize(QtCore.QSize(62, 40))
        self.ref_c_button_2.setMaximumSize(QtCore.QSize(62, 40))
        self.ref_c_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ref_c_button_2.setStyleSheet("QPushButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.ref_c_button_2.setObjectName("ref_c_button_2")
        self.z_axis_dro_layout_10.addWidget(self.ref_c_button_2)
        self.verticalLayout_55.addWidget(self.dros_c_layout)
        self.spacer_widget = QtWidgets.QWidget(self.widget_xyzc)
        self.spacer_widget.setObjectName("spacer_widget")
        self.verticalLayout_55.addWidget(self.spacer_widget)
        self.verticalLayout.addWidget(self.widget_xyzc)

        self.retranslateUi(dros_xyzc)
        QtCore.QMetaObject.connectSlotsByName(dros_xyzc)

    def retranslateUi(self, dros_xyzc):
        _translate = QtCore.QCoreApplication.translate
        dros_xyzc.setWindowTitle(_translate("dros_xyzc", "dros_xyzc"))
        self.zero_all_button.setText(_translate("dros_xyzc", "ALL"))
        self.zero_all_button.setProperty("rules", _translate("dros_xyzc", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_all_button.setProperty("MDICommand", _translate("dros_xyzc", "G10 L20 P{ch[0]} X0.0 Y0.0 Z0.0 C0.0"))
        self.work_column_header.setProperty("rules", _translate("dros_xyzc", "[{\"channels\": [{\"url\": \"status:g5x_index?text\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"ch[0] + \' WORK\'\\n\", \"name\": \"WCS Header\"}]"))
        self.machine_column_header.setText(_translate("dros_xyzc", "MACHINE"))
        self.dtg_column_header.setText(_translate("dros_xyzc", "DTG"))
        self.ref_all_button.setText(_translate("dros_xyzc", "REF ALL"))
        self.ref_all_button.setProperty("rules", _translate("dros_xyzc", "[{\"channels\": [{\"url\": \"status:all_axes_homed\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"\'HOMED\' if ch[0] else \'REF ALL\'\", \"name\": \"reference_all\"}, {\"name\": \"home_inhibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_all_button.setProperty("actionName", _translate("dros_xyzc", "machine.home.all"))
        self.zero_x_button.setText(_translate("dros_xyzc", "X RAD"))
        self.zero_x_button.setProperty("rules", _translate("dros_xyzc", "[{\"channels\": [{\"url\": \"status:g5x_index\", \"trigger\": true, \"type\": \"int\"}], \"property\": \"None\", \"expression\": \"\", \"name\": \"G5x Index\"}, {\"channels\": [{\"url\": \"status:gcodes\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"\'X DIA\' if \'G7\' in ch[0] else \'X RAD\'\", \"name\": \"diam_rad_mode_display\"}]"))
        self.zero_x_button.setProperty("MDICommand", _translate("dros_xyzc", "G10 L20 P{ch[0]} X0.0"))
        self.dro_entry_x_main.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.dro_entry_x_main.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.dro_entry_x_main.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.drolabel_machine_x.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.drolabel_machine_x.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.drolabel_machine_x.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.dro_dtg_x.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.dro_dtg_x.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.dro_dtg_x.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.ref_x_button_2.setText(_translate("dros_xyzc", "REF X"))
        self.ref_x_button_2.setProperty("rules", _translate("dros_xyzc", "[{\"name\": \"home_prohibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_x_button_2.setProperty("actionName", _translate("dros_xyzc", "machine.home.axis:x"))
        self.zero_y_button.setText(_translate("dros_xyzc", "Y"))
        self.zero_y_button.setProperty("rules", _translate("dros_xyzc", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_y_button.setProperty("MDICommand", _translate("dros_xyzc", "G10 L20 P{ch[0]} Y0.0"))
        self.dro_entry_y_main.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.dro_entry_y_main.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.dro_entry_y_main.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.drolabel_machine_y.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.drolabel_machine_y.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.drolabel_machine_y.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.drolabel_12.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.drolabel_12.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.drolabel_12.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.ref_y_button_2.setText(_translate("dros_xyzc", "REF Y"))
        self.ref_y_button_2.setProperty("rules", _translate("dros_xyzc", "[{\"name\": \"home_prohibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_y_button_2.setProperty("actionName", _translate("dros_xyzc", "machine.home.axis:y"))
        self.zero_z_button.setText(_translate("dros_xyzc", "Z"))
        self.zero_z_button.setProperty("rules", _translate("dros_xyzc", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_z_button.setProperty("MDICommand", _translate("dros_xyzc", "G10 L20 P{ch[0]} Z0.0"))
        self.dro_entry_z_main.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.dro_entry_z_main.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.dro_entry_z_main.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.drolabel_machine_z.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.drolabel_machine_z.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.drolabel_machine_z.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.dro_dtg_z.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.dro_dtg_z.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.dro_dtg_z.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.ref_z_button_2.setText(_translate("dros_xyzc", "REF Z"))
        self.ref_z_button_2.setProperty("rules", _translate("dros_xyzc", "[{\"name\": \"home_prohibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_z_button_2.setProperty("actionName", _translate("dros_xyzc", "machine.home.axis:z"))
        self.zero_c_button.setText(_translate("dros_xyzc", "C"))
        self.zero_c_button.setProperty("rules", _translate("dros_xyzc", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_c_button.setProperty("MDICommand", _translate("dros_xyzc", "G10 L20 P{ch[0]} C0.0"))
        self.dro_entry_c_main.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.dro_entry_c_main.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.dro_entry_c_main.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.drolabel_machine_c.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.drolabel_machine_c.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.drolabel_machine_c.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.dro_dtg_c.setProperty("inchFormat", _translate("dros_xyzc", "%9.4f"))
        self.dro_dtg_c.setProperty("millimeterFormat", _translate("dros_xyzc", "%10.3f"))
        self.dro_dtg_c.setProperty("degreeFormat", _translate("dros_xyzc", "%10.2f"))
        self.ref_c_button_2.setText(_translate("dros_xyzc", "REF C"))
        self.ref_c_button_2.setProperty("rules", _translate("dros_xyzc", "[{\"name\": \"home_inhibit\", \"property\": \"Enable\", \"expression\": \"not (ch[0] or ch[1] or ch[2] or ch[3])\", \"channels\": [{\"url\": \"status:joint.0.homing\", \"trigger\": true}, {\"url\": \"status:joint.1.homing\", \"trigger\": true}, {\"url\": \"status:joint.2.homing\", \"trigger\": true}, {\"url\": \"status:joint.3.homing\", \"trigger\": true}]}]"))
        self.ref_c_button_2.setProperty("actionName", _translate("dros_xyzc", "machine.home.axis:c"))
from qtpyvcp.widgets.button_widgets.action_button import ActionButton
from qtpyvcp.widgets.button_widgets.mdi_button import MDIButton
from qtpyvcp.widgets.display_widgets.dro_label import DROLabel
from qtpyvcp.widgets.display_widgets.status_label import StatusLabel
from qtpyvcp.widgets.input_widgets.dro_line_edit import DROLineEdit
import probe_basic_lathe_rc
import probe_basic_rc
