# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bb/work/probe_basic-pyqt5-x86/sources/debian/python3-probe-basic/usr/share/configs/probe_basic_lathe/user_dro_display/xzc_dros/offset_dros_xzc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_offset_dros_xzc(object):
    def setupUi(self, offset_dros_xzc):
        offset_dros_xzc.setObjectName("offset_dros_xzc")
        offset_dros_xzc.resize(493, 178)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(offset_dros_xzc.sizePolicy().hasHeightForWidth())
        offset_dros_xzc.setSizePolicy(sizePolicy)
        offset_dros_xzc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(offset_dros_xzc)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.x_axis_dro_layout = QtWidgets.QHBoxLayout()
        self.x_axis_dro_layout.setContentsMargins(-1, 6, -1, 6)
        self.x_axis_dro_layout.setSpacing(12)
        self.x_axis_dro_layout.setObjectName("x_axis_dro_layout")
        self.zero_x_button_offset = MDIButton(offset_dros_xzc)
        self.zero_x_button_offset.setEnabled(False)
        self.zero_x_button_offset.setMinimumSize(QtCore.QSize(55, 38))
        self.zero_x_button_offset.setMaximumSize(QtCore.QSize(55, 38))
        self.zero_x_button_offset.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_x_button_offset.setStyleSheet("MDIButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.zero_x_button_offset.setObjectName("zero_x_button_offset")
        self.x_axis_dro_layout.addWidget(self.zero_x_button_offset)
        self.axis_label_x = QtWidgets.QLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axis_label_x.sizePolicy().hasHeightForWidth())
        self.axis_label_x.setSizePolicy(sizePolicy)
        self.axis_label_x.setMinimumSize(QtCore.QSize(45, 35))
        self.axis_label_x.setMaximumSize(QtCore.QSize(45, 35))
        self.axis_label_x.setStyleSheet("QLabel{\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(238, 238, 236);\n"
"    font: 18pt \"Bebas Kai\";\n"
"}")
        self.axis_label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.axis_label_x.setObjectName("axis_label_x")
        self.x_axis_dro_layout.addWidget(self.axis_label_x)
        self.dro_entry_offset_x = DROLineEdit(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_entry_offset_x.sizePolicy().hasHeightForWidth())
        self.dro_entry_offset_x.setSizePolicy(sizePolicy)
        self.dro_entry_offset_x.setMinimumSize(QtCore.QSize(0, 38))
        self.dro_entry_offset_x.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dro_entry_offset_x.setFont(font)
        self.dro_entry_offset_x.setStyleSheet("QLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.dro_entry_offset_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_entry_offset_x.setObjectName("dro_entry_offset_x")
        self.x_axis_dro_layout.addWidget(self.dro_entry_offset_x)
        self.drolabel_work_x = DROLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_work_x.sizePolicy().hasHeightForWidth())
        self.drolabel_work_x.setSizePolicy(sizePolicy)
        self.drolabel_work_x.setMinimumSize(QtCore.QSize(0, 38))
        self.drolabel_work_x.setMaximumSize(QtCore.QSize(16777215, 38))
        self.drolabel_work_x.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_work_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_work_x.setProperty("referenceType", 0)
        self.drolabel_work_x.setProperty("axisNumber", 0)
        self.drolabel_work_x.setProperty("latheMode", 0)
        self.drolabel_work_x.setObjectName("drolabel_work_x")
        self.x_axis_dro_layout.addWidget(self.drolabel_work_x)
        self.work_offset_x = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_offset_x.sizePolicy().hasHeightForWidth())
        self.work_offset_x.setSizePolicy(sizePolicy)
        self.work_offset_x.setMinimumSize(QtCore.QSize(0, 38))
        self.work_offset_x.setMaximumSize(QtCore.QSize(16777215, 38))
        self.work_offset_x.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.work_offset_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.work_offset_x.setObjectName("work_offset_x")
        self.x_axis_dro_layout.addWidget(self.work_offset_x)
        self.g52_g92_x = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g52_g92_x.sizePolicy().hasHeightForWidth())
        self.g52_g92_x.setSizePolicy(sizePolicy)
        self.g52_g92_x.setMinimumSize(QtCore.QSize(0, 38))
        self.g52_g92_x.setMaximumSize(QtCore.QSize(16777215, 38))
        self.g52_g92_x.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.g52_g92_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.g52_g92_x.setObjectName("g52_g92_x")
        self.x_axis_dro_layout.addWidget(self.g52_g92_x)
        self.tool_offset_x = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_offset_x.sizePolicy().hasHeightForWidth())
        self.tool_offset_x.setSizePolicy(sizePolicy)
        self.tool_offset_x.setMinimumSize(QtCore.QSize(0, 38))
        self.tool_offset_x.setMaximumSize(QtCore.QSize(16777215, 38))
        self.tool_offset_x.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.tool_offset_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tool_offset_x.setObjectName("tool_offset_x")
        self.x_axis_dro_layout.addWidget(self.tool_offset_x)
        self.verticalLayout.addLayout(self.x_axis_dro_layout)
        self.z_axis_dro_layout = QtWidgets.QHBoxLayout()
        self.z_axis_dro_layout.setContentsMargins(-1, 1, -1, 1)
        self.z_axis_dro_layout.setSpacing(12)
        self.z_axis_dro_layout.setObjectName("z_axis_dro_layout")
        self.zero_z_button_offset = MDIButton(offset_dros_xzc)
        self.zero_z_button_offset.setEnabled(False)
        self.zero_z_button_offset.setMinimumSize(QtCore.QSize(55, 38))
        self.zero_z_button_offset.setMaximumSize(QtCore.QSize(55, 38))
        self.zero_z_button_offset.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_z_button_offset.setStyleSheet("MDIButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.zero_z_button_offset.setObjectName("zero_z_button_offset")
        self.z_axis_dro_layout.addWidget(self.zero_z_button_offset)
        self.axis_label_z = QtWidgets.QLabel(offset_dros_xzc)
        self.axis_label_z.setMinimumSize(QtCore.QSize(45, 35))
        self.axis_label_z.setMaximumSize(QtCore.QSize(45, 35))
        self.axis_label_z.setStyleSheet("QLabel{\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(238, 238, 236);\n"
"    font: 18pt \"Bebas Kai\";\n"
"}")
        self.axis_label_z.setAlignment(QtCore.Qt.AlignCenter)
        self.axis_label_z.setObjectName("axis_label_z")
        self.z_axis_dro_layout.addWidget(self.axis_label_z)
        self.dro_entry_offset_z = DROLineEdit(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_entry_offset_z.sizePolicy().hasHeightForWidth())
        self.dro_entry_offset_z.setSizePolicy(sizePolicy)
        self.dro_entry_offset_z.setMinimumSize(QtCore.QSize(0, 38))
        self.dro_entry_offset_z.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dro_entry_offset_z.setFont(font)
        self.dro_entry_offset_z.setStyleSheet("QLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.dro_entry_offset_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_entry_offset_z.setProperty("axisNumber", 2)
        self.dro_entry_offset_z.setObjectName("dro_entry_offset_z")
        self.z_axis_dro_layout.addWidget(self.dro_entry_offset_z)
        self.drolabel_work_z = DROLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_work_z.sizePolicy().hasHeightForWidth())
        self.drolabel_work_z.setSizePolicy(sizePolicy)
        self.drolabel_work_z.setMinimumSize(QtCore.QSize(0, 38))
        self.drolabel_work_z.setMaximumSize(QtCore.QSize(16777215, 38))
        self.drolabel_work_z.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_work_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_work_z.setProperty("referenceType", 0)
        self.drolabel_work_z.setProperty("axisNumber", 2)
        self.drolabel_work_z.setProperty("latheMode", 0)
        self.drolabel_work_z.setObjectName("drolabel_work_z")
        self.z_axis_dro_layout.addWidget(self.drolabel_work_z)
        self.work_offset_z = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_offset_z.sizePolicy().hasHeightForWidth())
        self.work_offset_z.setSizePolicy(sizePolicy)
        self.work_offset_z.setMinimumSize(QtCore.QSize(0, 38))
        self.work_offset_z.setMaximumSize(QtCore.QSize(16777215, 38))
        self.work_offset_z.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.work_offset_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.work_offset_z.setObjectName("work_offset_z")
        self.z_axis_dro_layout.addWidget(self.work_offset_z)
        self.g52_g92_z = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g52_g92_z.sizePolicy().hasHeightForWidth())
        self.g52_g92_z.setSizePolicy(sizePolicy)
        self.g52_g92_z.setMinimumSize(QtCore.QSize(0, 38))
        self.g52_g92_z.setMaximumSize(QtCore.QSize(16777215, 38))
        self.g52_g92_z.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.g52_g92_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.g52_g92_z.setObjectName("g52_g92_z")
        self.z_axis_dro_layout.addWidget(self.g52_g92_z)
        self.tool_offset_z = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_offset_z.sizePolicy().hasHeightForWidth())
        self.tool_offset_z.setSizePolicy(sizePolicy)
        self.tool_offset_z.setMinimumSize(QtCore.QSize(0, 38))
        self.tool_offset_z.setMaximumSize(QtCore.QSize(16777215, 38))
        self.tool_offset_z.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.tool_offset_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tool_offset_z.setObjectName("tool_offset_z")
        self.z_axis_dro_layout.addWidget(self.tool_offset_z)
        self.verticalLayout.addLayout(self.z_axis_dro_layout)
        self.c_axis_dro_layout = QtWidgets.QHBoxLayout()
        self.c_axis_dro_layout.setContentsMargins(-1, 1, -1, 1)
        self.c_axis_dro_layout.setSpacing(12)
        self.c_axis_dro_layout.setObjectName("c_axis_dro_layout")
        self.zero_c_button_offset = MDIButton(offset_dros_xzc)
        self.zero_c_button_offset.setEnabled(False)
        self.zero_c_button_offset.setMinimumSize(QtCore.QSize(55, 38))
        self.zero_c_button_offset.setMaximumSize(QtCore.QSize(55, 38))
        self.zero_c_button_offset.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero_c_button_offset.setStyleSheet("MDIButton {\n"
"       font: 15pt \"Bebas Kai\";\n"
"}")
        self.zero_c_button_offset.setObjectName("zero_c_button_offset")
        self.c_axis_dro_layout.addWidget(self.zero_c_button_offset)
        self.axis_label_c = QtWidgets.QLabel(offset_dros_xzc)
        self.axis_label_c.setMinimumSize(QtCore.QSize(45, 35))
        self.axis_label_c.setMaximumSize(QtCore.QSize(45, 35))
        self.axis_label_c.setStyleSheet("QLabel{\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(238, 238, 236);\n"
"    font: 18pt \"Bebas Kai\";\n"
"}")
        self.axis_label_c.setAlignment(QtCore.Qt.AlignCenter)
        self.axis_label_c.setObjectName("axis_label_c")
        self.c_axis_dro_layout.addWidget(self.axis_label_c)
        self.dro_entry_offset_c = DROLineEdit(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dro_entry_offset_c.sizePolicy().hasHeightForWidth())
        self.dro_entry_offset_c.setSizePolicy(sizePolicy)
        self.dro_entry_offset_c.setMinimumSize(QtCore.QSize(0, 38))
        self.dro_entry_offset_c.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dro_entry_offset_c.setFont(font)
        self.dro_entry_offset_c.setStyleSheet("QLineEdit{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    padding-right: 2px;\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.dro_entry_offset_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dro_entry_offset_c.setProperty("axisNumber", 5)
        self.dro_entry_offset_c.setObjectName("dro_entry_offset_c")
        self.c_axis_dro_layout.addWidget(self.dro_entry_offset_c)
        self.drolabel_work_c = DROLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drolabel_work_c.sizePolicy().hasHeightForWidth())
        self.drolabel_work_c.setSizePolicy(sizePolicy)
        self.drolabel_work_c.setMinimumSize(QtCore.QSize(0, 38))
        self.drolabel_work_c.setMaximumSize(QtCore.QSize(16777215, 38))
        self.drolabel_work_c.setStyleSheet("QLabel{\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"    padding-right: 2px;\n"
"}\n"
"\n"
"QLabel[style=\"unhomed\"]{\n"
"   color: red;\n"
"}\n"
"\n"
"QLabel[style=\"homing\"]{\n"
"   color: rgb(196, 160, 0);\n"
"}")
        self.drolabel_work_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drolabel_work_c.setProperty("referenceType", 0)
        self.drolabel_work_c.setProperty("axisNumber", 5)
        self.drolabel_work_c.setProperty("latheMode", 0)
        self.drolabel_work_c.setObjectName("drolabel_work_c")
        self.c_axis_dro_layout.addWidget(self.drolabel_work_c)
        self.work_offset_c = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_offset_c.sizePolicy().hasHeightForWidth())
        self.work_offset_c.setSizePolicy(sizePolicy)
        self.work_offset_c.setMinimumSize(QtCore.QSize(0, 38))
        self.work_offset_c.setMaximumSize(QtCore.QSize(16777215, 38))
        self.work_offset_c.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.work_offset_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.work_offset_c.setObjectName("work_offset_c")
        self.c_axis_dro_layout.addWidget(self.work_offset_c)
        self.g52_g92_c = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g52_g92_c.sizePolicy().hasHeightForWidth())
        self.g52_g92_c.setSizePolicy(sizePolicy)
        self.g52_g92_c.setMinimumSize(QtCore.QSize(0, 38))
        self.g52_g92_c.setMaximumSize(QtCore.QSize(16777215, 38))
        self.g52_g92_c.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.g52_g92_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.g52_g92_c.setObjectName("g52_g92_c")
        self.c_axis_dro_layout.addWidget(self.g52_g92_c)
        self.tool_offset_c = StatusLabel(offset_dros_xzc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_offset_c.sizePolicy().hasHeightForWidth())
        self.tool_offset_c.setSizePolicy(sizePolicy)
        self.tool_offset_c.setMinimumSize(QtCore.QSize(0, 38))
        self.tool_offset_c.setMaximumSize(QtCore.QSize(16777215, 38))
        self.tool_offset_c.setStyleSheet("StatusLabel{\n"
"    border-style: transparant;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 17pt \"Bebas Kai\";\n"
"}")
        self.tool_offset_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tool_offset_c.setObjectName("tool_offset_c")
        self.c_axis_dro_layout.addWidget(self.tool_offset_c)
        self.verticalLayout.addLayout(self.c_axis_dro_layout)

        self.retranslateUi(offset_dros_xzc)
        QtCore.QMetaObject.connectSlotsByName(offset_dros_xzc)

    def retranslateUi(self, offset_dros_xzc):
        _translate = QtCore.QCoreApplication.translate
        offset_dros_xzc.setWindowTitle(_translate("offset_dros_xzc", "offset_dros_xzc"))
        self.zero_x_button_offset.setText(_translate("offset_dros_xzc", "ZERO"))
        self.zero_x_button_offset.setProperty("rules", _translate("offset_dros_xzc", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_x_button_offset.setProperty("MDICommand", _translate("offset_dros_xzc", "G10 L20 P{ch[0]} X0.0"))
        self.axis_label_x.setText(_translate("offset_dros_xzc", "X"))
        self.drolabel_work_x.setProperty("inchFormat", _translate("offset_dros_xzc", "%9.4f"))
        self.drolabel_work_x.setProperty("millimeterFormat", _translate("offset_dros_xzc", "%10.3f"))
        self.drolabel_work_x.setProperty("degreeFormat", _translate("offset_dros_xzc", "%10.2f"))
        self.work_offset_x.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"trigger\": true, \"type\": \"tuple\", \"url\": \"status:g5x_offset\"}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][0])\", \"name\": \"New Rule\"}]"))
        self.g52_g92_x.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"trigger\": true, \"type\": \"tuple\", \"url\": \"status:g92_offset\"}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][0])\", \"name\": \"New Rule\"}]"))
        self.tool_offset_x.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"trigger\": true, \"type\": \"tuple\", \"url\": \"status:tool_offset\"}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][0])\", \"name\": \"New Rule\"}]"))
        self.zero_z_button_offset.setText(_translate("offset_dros_xzc", "ZERO"))
        self.zero_z_button_offset.setProperty("rules", _translate("offset_dros_xzc", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_z_button_offset.setProperty("MDICommand", _translate("offset_dros_xzc", "G10 L20 P{ch[0]} Z0.0"))
        self.axis_label_z.setText(_translate("offset_dros_xzc", "Z"))
        self.drolabel_work_z.setProperty("inchFormat", _translate("offset_dros_xzc", "%9.4f"))
        self.drolabel_work_z.setProperty("millimeterFormat", _translate("offset_dros_xzc", "%10.3f"))
        self.drolabel_work_z.setProperty("degreeFormat", _translate("offset_dros_xzc", "%10.2f"))
        self.work_offset_z.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"trigger\": true, \"type\": \"tuple\", \"url\": \"status:g5x_offset\"}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][2])\", \"name\": \"New Rule\"}]"))
        self.g52_g92_z.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"trigger\": true, \"type\": \"tuple\", \"url\": \"status:g92_offset\"}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][2])\", \"name\": \"New Rule\"}]"))
        self.tool_offset_z.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"url\": \"status:tool_offset\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][2])\", \"name\": \"tool offset\"}]"))
        self.zero_c_button_offset.setText(_translate("offset_dros_xzc", "ZERO"))
        self.zero_c_button_offset.setProperty("rules", _translate("offset_dros_xzc", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_c_button_offset.setProperty("MDICommand", _translate("offset_dros_xzc", "G10 L20 P{ch[0]} C0.0"))
        self.axis_label_c.setText(_translate("offset_dros_xzc", "C"))
        self.drolabel_work_c.setProperty("inchFormat", _translate("offset_dros_xzc", "%9.4f"))
        self.drolabel_work_c.setProperty("millimeterFormat", _translate("offset_dros_xzc", "%10.3f"))
        self.drolabel_work_c.setProperty("degreeFormat", _translate("offset_dros_xzc", "%10.2f"))
        self.work_offset_c.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"url\": \"status:g5x_offset\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][5])\", \"name\": \"New Rule\"}]"))
        self.g52_g92_c.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"url\": \"status:g92_offset\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][5])\", \"name\": \"New Rule\"}]"))
        self.tool_offset_c.setProperty("rules", _translate("offset_dros_xzc", "[{\"channels\": [{\"url\": \"status:tool_offset\", \"trigger\": true}], \"property\": \"Text\", \"expression\": \"\\\"{:.4f}\\\".format(ch[0][5])\", \"name\": \"tool offset\"}]"))
from qtpyvcp.widgets.button_widgets.mdi_button import MDIButton
from qtpyvcp.widgets.display_widgets.dro_label import DROLabel
from qtpyvcp.widgets.display_widgets.status_label import StatusLabel
from qtpyvcp.widgets.input_widgets.dro_line_edit import DROLineEdit
import probe_basic_rc
